### ISSUE TITLE
Improve error reporting

### ISSUE THREAD

**Issue by Xowap** [Xowap/typefit#14]

**Comment by sunitdeshpande** [comment]
Hey, nice work with typefit.  If no one is working on this issue, I would like to help.  Can you please add a little more description on this issue?

Thanks.

**Comment by Xowap** [comment]
Fantastic!

Well, the idea is the following: the error reporting right now is terrible as fuck because it just tells you that there is an error somewhere but you have to guess how to fix it.

I'm pretty sure that this will require a re-write of the fitting engine in order to have the errors properly formatted.

As to how to report errors, I think we should review what other libraries do and to find something that makes sense. So far I have no good idea.

Basically I have two approaches in mind:

- Either print JSON-ish dump of the input data with errored lines commented
- Either print the data model tree and print examples of errors encountered to make things match this model

However, there is one very large issue which is that

- Models can be recursive
- `Union` types create some branching

In short it's a complicated problem to solve nicely and I'm very open to input about that and to ease you into implementing it if you're still interested (I mean, it's clearly not the easiest ticket to get into the project with :) )

**Comment by sunitdeshpande** [comment]
Sure.

I will think over it and get back on this issue. Do let me know if there are some other issues where I can be of help.

Thanks.

**Comment by Xowap** [comment]
Thanks!

A simple one could be like #8, which would be pretty straightforward to implement I think. I'll write a description on it.

**Comment by Xowap** [comment]
A few ideas:

- Create a stand-alone web server that helps you debug your data
  - Stand-alone form that lets you validate any JSON against any importable type
  - Service that listens to decoding errors and allows you to analyze them
- Make it so that the validation errors can be programmatically used (by the web interface quoted above or by an external tool like IDE debuggers)

This still doesn't tell us what the validation output should look like, though

**Comment by Xowap** [comment]
Done
