### ISSUE TITLE
ModuleNotFoundError: No module named 'httpx'

### ISSUE THREAD

**Issue by VaibhavKulkarni008** [Xowap/typefit#15]
### Description:
After installing the _typefit_ library getting this error while importing **api** module.

### Error Traceback:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.virtualenvs/typefit_test/lib/python3.7/site-packages/typefit/api.py", line 6, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'

### Steps to reproduce:
- Install the typefit library
- Open python interactive shell
- Run following code
`from typefit import api`

### Expected Behaviour:
Should be able to import the **api** module without any errors.

**Comment by Xowap** [comment]
Ah yes, that's related to the fact that the `httpx` dependency is optional. That's poorly documented.

Try to `pip install typefit[api]` (or even `pip install typefit[api,dates]` to also manage date/time narrows)

**Comment by VaibhavKulkarni008** [comment]
We can make it mandatory package during the installation, because right now it is listed as optional dependency in _pyproject.toml_ file.

**Comment by Xowap** [comment]
The initial scope of Typefit was just fitting types but then the API part took a huge part because I realized that why not.

Maybe I'll take the problem the other way and make the dependencies mandatory until people complain about useless dependencies, that will probably avoid issues.

Stay tuned :)

**Comment by VaibhavKulkarni008** [comment]
That seems reasonable.

Do let me know if there are some other issues where I can be of help.

Thanks.

**Comment by Xowap** [comment]
Changed dependencies declaration, this should not happen at next release
